version: "3.8"

services:
  development-machine:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    container_name: {{cookiecutter.nuxt_project_name}}

    volumes:
      - ..:/workspace/{{cookiecutter.nuxt_project_name}}:cached

    command: sleep infinity
