version: "3.8"

services:
  development-machine:
    build:
      context: ..
      dockerfile: {{ cookiecutter.devcontainer_folder_name }}/Dockerfile

    volumes:
      - ..:/workspace/{{ cookiecutter.project_name }}:cached
      - postgres_data:/var/lib/postgresql/data

    command: sleep infinity

volumes:
  postgres_data:
