//! SeaORM Entity. Generated by sea-orm-codegen 0.5.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "apps")]
pub struct Model {
    pub slug: Uuid,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub name: String,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::deploys::Entity")]
    Deploys,
}

impl Related<super::deploys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Deploys.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
