[package]
name = "cinder"
version = "0.1.0"
edition = "2021"
description = "A small webserver to handle dokku based deployments"
repository = "https://github.com/IgnisDa/developrs"
categories = ["web-server"]
authors = ["Diptesh Choudhuri <ignisda2001@gmail.com>"]
readme = "README.md"
license = "MIT"


[dependencies]
actix-web = "3"
chrono = { version = "0.4.19", features = ["serde"] }
dotenv = "0.15"
env_logger = "0.9.0"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "0.8", features = ["serde", "v4"] }

[dependencies.sea-orm]
version = "0.5.0"
features = ["sqlx-postgres", "macros", "runtime-async-std-native-tls", "debug-print"]
default-features = false
