[package]
name = "cinder"
version = "0.1.0"
edition = "2021"
description = "A small webserver to handle dokku based deployments"
repository = "https://github.com/IgnisDa/developrs"
categories = ["web-server"]
authors = ["Diptesh Choudhuri <ignisda2001@gmail.com>"]
readme = "README.md"
license = "MIT"


[dependencies]
actix-web = "3"
chrono = { version = "0.4.19", features = ["serde"] }
diesel = { version = "1.4.8", features = ["postgres", "r2d2", "chrono", "uuidv07"] }
diesel_migrations = "1.4"
dotenv = "0.15"
env_logger = "0.9.0"
failure = "0.1.8"
futures = "0.3.1"
lazy_static = "1.4"
log = "0.4"
r2d2 = "0.8"
sea-orm = { version = "0.5.0", features = [ "sqlx-postgres", "runtime-actix-rustls", "macros", "debug-print"], default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "0.8", features = ["serde", "v4"] }

[dev-dependencies]
actix-rt = "2.6.0"
