name: "Cinder"
description: "Calculate whether a particular app needs to be redeployed due to changes"
inputs:
  cinder-endpoint: # id of input
    description: "The endpoint where cinder is running on dokku installation"
    required: true
outputs:
  affected: # id of output
    description: "The names of the projects that have been affected"
runs:
  using: "node16"
  main: "index.js"
