name: Docker
on:
  push:
    tags:
      - "docker-v*"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get build args
        id: args
        run: echo "::set-output name=date::$(date -u +'%Y-%m-%dT')"

      - name: Build and push latest tag
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          build-args: BUILD_DATE=${{ steps.args.outputs.date }}
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ignisda/developr-workspace:latest

      - name: Build and push rust tag
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./docker/rust.Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ignisda/developr-workspace:rust
