name: Docker

on:
  push:
    tags:
      - 'docker-v*'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ignisda
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get build args
        id: args
        run: echo "date=$(date -u +'%Y-%m-%dT')" >> $GITHUB_OUTPUT

      - name: Build and push latest tag
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: BUILD_DATE=${{ steps.args.outputs.date }}
          file: ./docker/Dockerfile
          push: true
          tags: ignisda/archlinux:latest
